### ISSUE TITLE
关于外链工厂获取图片的link问题？

### ISSUE THREAD

**Issue by dondurma** [T5750/T5750.github.io#6]
楼主，我看到你介绍在yili主题中添加相册的功能http://evaneo.top/2018/03/09/blogPhotos/，里面有关于从图片工厂获取图片的link，我也试着注册一个外链工厂的账号，并上传图片，就是不知道怎么获取link,您所说的link是指图片的url吗？我在ins.json文件中的link地方添加了图片的url，为什么不显示图片呢？

**Comment by T5750** [comment]
@dondurma 你好，对的。
例如，外链工厂中的图片URL链接为http://www.wailian.work/images/2018/03/08/LongTailedBushtits.jpg
那么，`ins.json`中对应为`2018/03/08/LongTailedBushtits`
结合开发者工具再试试

**Comment by dondurma** [comment]
嗯嗯，谢谢，还有就是能不能换成七牛云的url呢？

**Comment by T5750** [comment]
不用谢的，七牛云没试过，可以试着在`ins.js`中更换前缀等

**Comment by dondurma** [comment]
嗯 我替换了ins.js中minSrc 和 src后面的链接改为我的七牛云前缀，相册的首页不显示，点击具体某张图片进入详情后才显示图片？还有一个问题就是如果不是.jpg格式的图片进入详情也无法显示，ins.js文件中是不是将图片格式限制死了呢？

**Comment by T5750** [comment]
查看`minSrc`是否与七牛云中的缩略图一致，效果参考http://evaneo.top/photos/index.html
`ins.js`中有格式限制，根据实际需要修改

**Comment by dondurma** [comment]
嗯嗯，谢谢，还有一个问题，这个图片点击详情查看的时候能按照图片本身的比例显示吗？如果按照正方形显示有些图片会被压缩很难看。

**Comment by T5750** [comment]
不用谢的，适配手机，调试`ins.js`试试吧
